### PR TITLE
fix: throw on invalid URLs

### LINKED ISSUE #35: Invalid URLs don't throw errors in IE
If I try to create a new URL with the value "invalidUrl", instead of throwing an error it creates a new URL with the value appended to the current location (e.g. https://google.com/invalidUrl).

On other browsers (at least Chrome and Edge) it seems to work fine.

### LINKED ISSUE #37: Constructor should throw when no base is given for relative URLs
The following code should throw an `Invalid URL` error:

```javascript
new URL('/foo')
```

As of now, in both IE11 and Safari, `window.location.href` is assumed as `base`.

### PR DESCRIPTION
**Pull request by acifani**
Throw when provided with invalid url without a base, e.g.
```js
new URL('something')
```

**NB:** I have only tested this manually in IE11 and Chrome 49, not sure on how to proceed with running the project's test suites. Help is very welcome

Fixes #35 
Fixes #37

### CODE REVIEW

**Comment by lifaon74** [comment]
Thanks to you. Nice trick by the way ;)

**Comment by dvelasquez** [comment]
@lifaon74 Hey, I think this package with this fix has not been released yet. Can you please upload the new package to npm?

Thanks!!!

**Comment by odimodugno** [comment]
Hi can you upload the package on npm with the fix pls?

**Comment by lifaon74** [comment]
v1.1.9 released. sorry for the delay

**Pull request merged**
