### PR TITLE
Detect cross-origin error, e.g. in IE11, and optimize.

### PR DESCRIPTION
**Pull request by kmashint**
First, thanks for this polyfill for URL and URLSearchParams!

After some testing on IE11, I found there are security issues preventing use of a cross-origin base, so I made a more obvious error out of that situation.  I didn't understand the use of `window.doc = doc;` so I removed that.

I also optimized the use of the separate doc and base to only be necessary if the given base is different from the current global.location.href.

There's also a minor improvement to the URLSearchParams toString() where using an Array join("&") prevents repeating re-concatenation of strings.

### CODE REVIEW

**Comment by lifaon74** [comment]
Wow, great job ! I'll run the tests and publish on npm tomorrow. Thanks a lot.

**Comment by kmashint** [comment]
@lifaon74 With more testing I'm seeing some discrepancies with this ... I'll work on another patch later today.

**Comment by kmashint** [comment]
@lifaon74 I think it's OK.  I'll still do some more testing.

**Comment by lifaon74** [comment]
Ok, fully tested and published

**Pull request merged**
